### ISSUE TITLE
Added to lang-ext wiki

### ISSUE THREAD

**Issue by louthy** [NickDarvey/LanguageExt.AspNetCore#1]
Hi Nick, I have added this project to the lang-ext wiki: https://github.com/louthy/language-ext/wiki

If you feel like you'd rather not have the attention, please let me know and I'll remove it.

Is there more we can do to support ASP.NET Core?  I don't use it enough to have any strong views on it.

**Comment by NickDarvey** [comment]
That's cool, thanks for sharing. It's hell sparse in here, but you spurred me on to add some more extensions. 

To be honest, it's a little while since I've used lang-ext and ASP.NET Core together, so I haven't come across any new ones. (I think I have a chance to use the combo again soon so you might see a flurry of updates.)

**Comment by louthy** [comment]
Heh, good stuff :)
